namespace NaturalQuery.Models;

/// <summary>
/// The outcome of a dry-run: the generated, validated query and its estimated
/// cost (when the backend supports estimation), awaiting caller approval before
/// execution.
/// </summary>
public class QueryPreview
{
    /// <summary>The generated, validated SQL query.</summary>
    public string Sql { get; set; } = string.Empty;

    /// <summary>Recommended chart type for visualization.</summary>
    public string ChartType { get; set; } = "table";

    /// <summary>Report title generated by the LLM.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Brief description of the report.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Estimated cost, when a cost estimator is registered.</summary>
    public QueryCostEstimate? EstimatedCost { get; set; }

    /// <summary>Correlation identifier for tracing the approval flow.</summary>
    public string? CorrelationId { get; set; }
}
