namespace NaturalQuery.Models;

/// <summary>
/// Result of a natural language query interpretation and execution.
/// </summary>
public class QueryResult
{
    /// <summary>The generated SQL query.</summary>
    public string Sql { get; set; } = string.Empty;

    /// <summary>Recommended chart type for visualization.</summary>
    public string ChartType { get; set; } = "table";

    /// <summary>Report title generated by the LLM.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Brief description of the report.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Drill-down suggestions for follow-up queries.</summary>
    public List<string> Suggestions { get; set; } = new();

    /// <summary>Chart data points (for non-table results).</summary>
    public List<DataPoint>? ChartData { get; set; }

    /// <summary>Table data (for table results).</summary>
    public List<Dictionary<string, string>>? TableData { get; set; }

    /// <summary>Total tokens consumed by the LLM.</summary>
    public int TokensUsed { get; set; }

    /// <summary>Execution time in milliseconds.</summary>
    public long ElapsedMs { get; set; }

    /// <summary>True when the result was truncated at the configured maximum row count.</summary>
    public bool Truncated { get; set; }

    /// <summary>Correlation identifier linking this response to server-side logs and audit records.</summary>
    public string? CorrelationId { get; set; }

    /// <summary>True when prompt-injection screening flagged the question (warn mode).</summary>
    public bool InjectionFlagged { get; set; }
}
